#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyxattr
Version  : 0.6.1
Release  : 3
URL      : https://files.pythonhosted.org/packages/36/1d/1a5f3165f330e1a0427636f2bd995dbcc02d0f7660e89458d64806a2ed1e/pyxattr-0.6.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/36/1d/1a5f3165f330e1a0427636f2bd995dbcc02d0f7660e89458d64806a2ed1e/pyxattr-0.6.1.tar.gz
Summary  : Filesystem extended attributes for python
Group    : Development/Tools
License  : LGPL-2.1
Requires: pyxattr-python3
Requires: pyxattr-license
Requires: pyxattr-python
BuildRequires : buildreq-distutils3

%description
implements extended attributes manipulation. It is a wrapper on top
        of the attr C library - see attr(5).

%package license
Summary: license components for the pyxattr package.
Group: Default

%description license
license components for the pyxattr package.


%package python
Summary: python components for the pyxattr package.
Group: Default
Requires: pyxattr-python3

%description python
python components for the pyxattr package.


%package python3
Summary: python3 components for the pyxattr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyxattr package.


%prep
%setup -q -n pyxattr-0.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535987569
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pyxattr
cp COPYING %{buildroot}/usr/share/doc/pyxattr/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/pyxattr/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
