#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF66E3E419F84F4DE (iusty@k1024.org)
#
Name     : pyxattr
Version  : 0.7.1
Release  : 8
URL      : https://files.pythonhosted.org/packages/cf/b1/7ed931d98b5a91a59b69fcc2860e5b720a22ed1ddb85268415181c9b0986/pyxattr-0.7.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/cf/b1/7ed931d98b5a91a59b69fcc2860e5b720a22ed1ddb85268415181c9b0986/pyxattr-0.7.1.tar.gz
Source1 : https://files.pythonhosted.org/packages/cf/b1/7ed931d98b5a91a59b69fcc2860e5b720a22ed1ddb85268415181c9b0986/pyxattr-0.7.1.tar.gz.asc
Summary  : A python extension module that allows you to manipulate the extended attributes.
Group    : Development/Tools
License  : LGPL-2.1
Requires: pyxattr-license = %{version}-%{release}
Requires: pyxattr-python = %{version}-%{release}
Requires: pyxattr-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev

%description
# pyxattr
This is the pyxattr module, a Python extension module which gives access
to the extended attributes for filesystem objects available in some
operating systems.

%package license
Summary: license components for the pyxattr package.
Group: Default

%description license
license components for the pyxattr package.


%package python
Summary: python components for the pyxattr package.
Group: Default
Requires: pyxattr-python3 = %{version}-%{release}

%description python
python components for the pyxattr package.


%package python3
Summary: python3 components for the pyxattr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyxattr package.


%prep
%setup -q -n pyxattr-0.7.1
cd %{_builddir}/pyxattr-0.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1575395325
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyxattr
cp %{_builddir}/pyxattr-0.7.1/COPYING %{buildroot}/usr/share/package-licenses/pyxattr/9a1929f4700d2407c70b507b3b2aaf6226a9543c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyxattr/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
